startFadeIn=18:00
endFadeIn=18:45
startFadeOut=20:45
endFadeOut=21:30
blend=add
rotate=false
source=./aurora.png
biomes=snowy_tundra ice_spikes deep_frozen_ocean snowy_plains ice_spikes grove snowy_slopes frozen_peaks jagged_peaks frozen_ocean frozen_river snowy_tundra snowy_mountains snowy_beach snowy_taiga taiga
weather=clear